// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scorely-landing/AccessibilityFirst.tsx": () => import("../components/mockups/scorely-landing/AccessibilityFirst.tsx"),
  "./components/mockups/scorely-landing/AffordanceFirst.tsx": () => import("../components/mockups/scorely-landing/AffordanceFirst.tsx"),
  "./components/mockups/scorely-landing/ArcadeCabinet.tsx": () => import("../components/mockups/scorely-landing/ArcadeCabinet.tsx"),
  "./components/mockups/scorely-landing/BeforeAfter.tsx": () => import("../components/mockups/scorely-landing/BeforeAfter.tsx"),
  "./components/mockups/scorely-landing/BentoGrid.tsx": () => import("../components/mockups/scorely-landing/BentoGrid.tsx"),
  "./components/mockups/scorely-landing/ChallengePodium.tsx": () => import("../components/mockups/scorely-landing/ChallengePodium.tsx"),
  "./components/mockups/scorely-landing/FeatureTabs.tsx": () => import("../components/mockups/scorely-landing/FeatureTabs.tsx"),
  "./components/mockups/scorely-landing/FullWidthStack.tsx": () => import("../components/mockups/scorely-landing/FullWidthStack.tsx"),
  "./components/mockups/scorely-landing/HierarchyClear.tsx": () => import("../components/mockups/scorely-landing/HierarchyClear.tsx"),
  "./components/mockups/scorely-landing/InstantStart.tsx": () => import("../components/mockups/scorely-landing/InstantStart.tsx"),
  "./components/mockups/scorely-landing/LiveLobby.tsx": () => import("../components/mockups/scorely-landing/LiveLobby.tsx"),
  "./components/mockups/scorely-landing/LiveScoreboard.tsx": () => import("../components/mockups/scorely-landing/LiveScoreboard.tsx"),
  "./components/mockups/scorely-landing/NeonTypography.tsx": () => import("../components/mockups/scorely-landing/NeonTypography.tsx"),
  "./components/mockups/scorely-landing/ProductLed.tsx": () => import("../components/mockups/scorely-landing/ProductLed.tsx"),
  "./components/mockups/scorely-landing/ScoreTicker.tsx": () => import("../components/mockups/scorely-landing/ScoreTicker.tsx"),
  "./components/mockups/scorely-landing/StoryFirst.tsx": () => import("../components/mockups/scorely-landing/StoryFirst.tsx"),
  "./components/mockups/scorely-landing/TerminalMode.tsx": () => import("../components/mockups/scorely-landing/TerminalMode.tsx"),
  "./components/mockups/scorely-landing/TrophyGrand.tsx": () => import("../components/mockups/scorely-landing/TrophyGrand.tsx"),
  "./components/mockups/scorely-landing/TrophyPodium.tsx": () => import("../components/mockups/scorely-landing/TrophyPodium.tsx"),
  "./components/mockups/scorely-landing/TrophyPolished.tsx": () => import("../components/mockups/scorely-landing/TrophyPolished.tsx")
};
